import { p as push, q as push_element, u as pop_element, n as pop, F as FILENAME } from "../../../chunks/index.js";
import "clsx";
import { H as Header } from "../../../chunks/header.js";
_page[FILENAME] = "src/routes/card-info/+page.svelte";
function _page($$payload, $$props) {
  push(_page);
  Header($$payload);
  $$payload.out += `<!----> <div class="card-and-comment-main-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 5, 0);
  $$payload.out += `<div class="cardinfo-main-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 6, 0);
  $$payload.out += `<div class="cardinfo-button-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 7, 4);
  $$payload.out += `<div class="card-status svelte-2qopeu">`;
  push_element($$payload, "div", 8, 8);
  $$payload.out += `საშუალო</div>`;
  pop_element();
  $$payload.out += ` <div class="card-status card-department svelte-2qopeu">`;
  push_element($$payload, "div", 9, 8);
  $$payload.out += `დიზაინი</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <h1>`;
  push_element($$payload, "h1", 11, 4);
  $$payload.out += `Redberry-ს საიტის ლენდინგის დიზაინი</h1>`;
  pop_element();
  $$payload.out += ` <p>`;
  push_element($$payload, "p", 12, 4);
  $$payload.out += `მიზანია რომ შეიქმნას თანამედროვე, სუფთა და ფუნქციონალური დიზაინი, რომელიც უზრუნველყოფს მარტივ ნავიგაციას და მკაფიო ინფორმაციის გადაცემას. დიზაინი უნდა იყოს ადაპტირებადი (responsive), გამორჩეული ვიზუალით, მინიმალისტური სტილით და ნათელი ტიპოგრაფიით.</p>`;
  pop_element();
  $$payload.out += ` <div>`;
  push_element($$payload, "div", 13, 4);
  $$payload.out += `<p>`;
  push_element($$payload, "p", 14, 8);
  $$payload.out += `დავალებების დეტალები</p>`;
  pop_element();
  $$payload.out += ` <div class="cardinfo-info-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 15, 8);
  $$payload.out += `<img alt="clock">`;
  push_element($$payload, "img", 16, 12);
  pop_element();
  $$payload.out += ` <div>`;
  push_element($$payload, "div", 17, 12);
  $$payload.out += `სტატუსი</div>`;
  pop_element();
  $$payload.out += ` <select>`;
  push_element($$payload, "select", 18, 12);
  $$payload.out += `მზად ტესტირებისთვის</select>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <div class="cardinfo-info-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 20, 8);
  $$payload.out += `<img alt="person">`;
  push_element($$payload, "img", 21, 12);
  pop_element();
  $$payload.out += ` <div>`;
  push_element($$payload, "div", 22, 12);
  $$payload.out += `თანამშრომელი</div>`;
  pop_element();
  $$payload.out += ` <img>`;
  push_element($$payload, "img", 23, 12);
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <div class="cardinfo-info-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 25, 8);
  $$payload.out += `<img alt="date">`;
  push_element($$payload, "img", 26, 12);
  pop_element();
  $$payload.out += ` <div>`;
  push_element($$payload, "div", 27, 12);
  $$payload.out += `დავალების ვადა</div>`;
  pop_element();
  $$payload.out += ` <p>`;
  push_element($$payload, "p", 28, 12);
  $$payload.out += `ორშ - 02/2/2025</p>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <div class="comment-section-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 32, 4);
  $$payload.out += `<div class="comment-section">`;
  push_element($$payload, "div", 33, 8);
  $$payload.out += `<div class="comment-input-field svelte-2qopeu">`;
  push_element($$payload, "div", 34, 12);
  $$payload.out += `<input class="comment-input svelte-2qopeu" placeholder="დაწერე კომენტარი">`;
  push_element($$payload, "input", 35, 16);
  pop_element();
  $$payload.out += ` <button class="comment-button svelte-2qopeu">`;
  push_element($$payload, "button", 36, 16);
  $$payload.out += `დააკომენტარე</button>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <div class="comment-amount-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 38, 12);
  $$payload.out += `<h2>`;
  push_element($$payload, "h2", 39, 16);
  $$payload.out += `კომენტარები</h2>`;
  pop_element();
  $$payload.out += ` <p class="comment-amount svelte-2qopeu">`;
  push_element($$payload, "p", 40, 16);
  $$payload.out += `3</p>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += ` <div class="comment-user-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 44, 8);
  $$payload.out += `<img alt="profilepic">`;
  push_element($$payload, "img", 45, 12);
  pop_element();
  $$payload.out += ` <div class="comment-info svelte-2qopeu">`;
  push_element($$payload, "div", 46, 12);
  $$payload.out += `<p class="comment-username svelte-2qopeu">`;
  push_element($$payload, "p", 47, 16);
  $$payload.out += `სახელი</p>`;
  pop_element();
  $$payload.out += ` <p>`;
  push_element($$payload, "p", 48, 16);
  $$payload.out += `კომენტარის ტექსტი</p>`;
  pop_element();
  $$payload.out += ` <div class="comment-reply-wrapper svelte-2qopeu">`;
  push_element($$payload, "div", 49, 16);
  $$payload.out += `<img alt="arrow">`;
  push_element($$payload, "img", 50, 20);
  pop_element();
  $$payload.out += ` <p>`;
  push_element($$payload, "p", 51, 20);
  $$payload.out += `უპასყხე</p>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  $$payload.out += `</div>`;
  pop_element();
  pop();
}
_page.render = function() {
  throw new Error("Component.render(...) is no longer valid in Svelte 5. See https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes for more information");
};
export {
  _page as default
};
